import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { type Questions, type SystemOneResult } from "@typesafe-ai/sdk";

import { loadConfig } from "../src/config.js";
import { MAX_EXCERPT_CHARS } from "../src/packs/code-audit.js";
import { getPack } from "../src/packs/index.js";
import {
  collectScanFiles,
  complexityHeuristic,
  extractImports,
  extractSignals,
  formatSummaryTable,
  inferLanguage,
  inferRoleHint,
  listScanPaths,
  parseScanArgs,
  pathHeuristics,
  primaryConcern,
  problemSeverity,
  rankForPass2,
  runScan,
  shouldIncludePath,
  toPackState,
  type ScanRecord,
} from "../src/scan.js";
import { validatePackState } from "../src/validate.js";

const root = fileURLToPath(new URL("..", import.meta.url));

function writeFixture(dir: string): void {
  const files: Record<string, string> = {
    ".gitignore": "secret.bin\nignored-dir/\n",
    "README.md": "# fixture\n",
    "src/billing/invoice.ts": [
      'import { money } from "./money";',
      'import { fmt } from "../fmt";',
      "export function total(n: number) {",
      "  if (n > 0) return n;",
      "  return 0;",
      "}",
      "",
    ].join("\n"),
    "src/auth/login.ts": ['import { jwt } from "./jwt";', "export function login() { return jwt; }", ""].join("\n"),
    "src/auth/login.test.ts": [
      'import { test } from "node:test";',
      'import { login } from "./login";',
      'test("login", () => { login(); });',
      "",
    ].join("\n"),
    "db/migrations/001_init.sql": "CREATE TABLE invoices (id int);\n",
    "generated/out.ts": "export const generated = 1;\n",
    "node_modules/pkg/index.js": "module.exports = 1;\n",
    "package-lock.json": "{}\n",
    "photo.png": "not-really-an-image",
    "secret.bin": "secret",
    "ignored-dir/skip.ts": "export const nope = 1;\n",
    "src/generated_header.ts": "// @generated by tool\nexport const z = 1;\n",
    "dist/bundle.js": "console.log(1);\n",
  };
  for (const [rel, body] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, body);
  }
}

function runCli(args: string[], extraEnv: NodeJS.ProcessEnv, entry = "src/index.ts") {
  return spawnSync(process.execPath, ["--import", "tsx", entry, ...args], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, TYPESAFE_API_KEY: "", ...extraEnv },
  });
}

function fakeAnswers(severity: number, concern: string): SystemOneResult<Questions>["answers"] {
  return {
    wrong_layer: { type: "noul", noul: 0.1 },
    blast_radius: { type: "noul", noul: 0.2 },
    missing_verification: { type: "noul", noul: concern === "verification" ? 0.8 : 0.2 },
    secret_or_credential_risk: { type: "noul", noul: 0.05 },
    inefficiency: { type: "noul", noul: 0.08 },
    dead_or_premature_abstraction: { type: "noul", noul: 0.12 },
    problem_severity: {
      type: "score",
      score: severity,
      confidence: 0.6,
      legend: { 0: "clean", 1: "local", 2: "cross", 3: "block" },
      probabilities: { 1: 0.7 },
    },
    change_cost: {
      type: "score",
      score: 0.8,
      confidence: 0.65,
      legend: { 0: "cheap", 1: "module", 2: "cross", 3: "risky" },
      probabilities: { 1: 0.6 },
    },
    primary_concern: {
      type: "choice",
      choice: concern,
      confidence: 0.72,
      probabilities: { [concern]: 0.72 },
    },
  };
}

test("shouldIncludePath skips binaries, lockfiles, and generated dirs", () => {
  assert.equal(shouldIncludePath("src/app.ts"), true);
  assert.equal(shouldIncludePath("package-lock.json"), false);
  assert.equal(shouldIncludePath("yarn.lock"), false);
  assert.equal(shouldIncludePath("photo.png"), false);
  assert.equal(shouldIncludePath("node_modules/pkg/index.js"), false);
  assert.equal(shouldIncludePath("dist/bundle.js"), false);
  assert.equal(shouldIncludePath(".git/config"), false);
  assert.equal(shouldIncludePath("generated/out.ts"), false);
  assert.equal(shouldIncludePath("vendor/lib.go"), false);
  assert.equal(shouldIncludePath("app.min.js"), false);
  assert.equal(shouldIncludePath(".env"), false);
  assert.equal(shouldIncludePath(".env.local"), false);
  assert.equal(shouldIncludePath(".env.example"), true);
});

test("signal extraction: imports, loc, complexity, path heuristics, nearby tests", () => {
  const invoice = [
    'import { money } from "./money";',
    'import fs from "node:fs";',
    "export function total(n: number) {",
    "  if (n > 0 && n < 10) return n;",
    "  return 0;",
    "}",
  ].join("\n");
  const all = ["src/billing/invoice.ts", "src/billing/invoice.test.ts", "src/auth/login.ts"];
  const signals = extractSignals("src/billing/invoice.ts", invoice, all);
  assert.equal(signals.loc, 6);
  assert.ok(signals.import_count >= 2);
  assert.ok(signals.top_imports.includes("money"));
  assert.ok(signals.top_imports.includes("node:fs") || signals.top_imports.includes("fs"));
  assert.equal(signals.has_tests_nearby, true);
  assert.equal(signals.touches_money, true);
  assert.equal(signals.touches_auth, false);
  assert.equal(signals.touches_migration, false);
  assert.equal(signals.is_generated, false);
  assert.ok(signals.complexity_heuristic >= 1);

  assert.deepEqual(pathHeuristics("src/auth/session.ts"), {
    touches_money: false,
    touches_auth: true,
    touches_migration: false,
  });
  assert.deepEqual(pathHeuristics("db/migrations/001.sql"), {
    touches_money: false,
    touches_auth: false,
    touches_migration: true,
  });
  assert.equal(inferLanguage("src/a.ts"), "ts");
  assert.equal(inferLanguage("db/x.sql"), "sql");
  assert.equal(inferRoleHint("src/billing/invoice.ts"), "domain");
  assert.equal(inferRoleHint("src/auth/login.ts"), "infra");
  assert.equal(inferRoleHint("src/auth/login.test.ts"), "test");
  assert.equal(inferRoleHint("db/migrations/001.sql"), "db");
  assert.ok(extractImports("from pathlib import Path\nimport os\n").includes("pathlib"));
  assert.ok(extractImports("from pathlib import Path\nimport os\n").includes("os"));
  assert.ok(complexityHeuristic("if (a) { for (x of y) {} }") >= 2);
});

test("toPackState drops touches_migration and stays valid code_audit state", () => {
  const pack = getPack("code_audit");
  const state = toPackState({
    path: "src/billing/invoice.ts",
    language: "ts",
    role_hint: "domain",
    signals: {
      loc: 6,
      import_count: 2,
      top_imports: ["money", "fmt"],
      has_tests_nearby: true,
      touches_money: true,
      touches_auth: false,
      touches_migration: true,
      is_generated: false,
      complexity_heuristic: 2,
    },
    repo_context: "scan fixture: src/billing",
  });
  assert.equal("excerpt" in state, false);
  const signals = state.signals as Record<string, unknown>;
  assert.equal("touches_migration" in signals, false);
  assert.equal(signals.touches_money, true);
  assert.doesNotThrow(() => validatePackState(pack, state));

  const pass2 = toPackState(
    {
      path: "src/billing/invoice.ts",
      language: "ts",
      role_hint: "domain",
      signals: {
        loc: 1,
        import_count: 0,
        top_imports: [],
        has_tests_nearby: false,
        touches_money: true,
        touches_auth: false,
        touches_migration: false,
        is_generated: false,
        complexity_heuristic: 0,
      },
      repo_context: "scan fixture",
    },
    "x".repeat(MAX_EXCERPT_CHARS + 50),
  );
  assert.equal((pass2.excerpt as string).length, MAX_EXCERPT_CHARS);
  assert.doesNotThrow(() => validatePackState(pack, pass2));
});

test("dry-run walk on a tiny fixture tree skips junk and keeps signals", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "mcp-jev-scan-"));
  writeFixture(dir);
  const listed = listScanPaths(dir);
  assert.ok(listed.includes("src/billing/invoice.ts"));
  assert.ok(listed.includes("src/auth/login.ts"));
  assert.ok(listed.includes("db/migrations/001_init.sql"));
  assert.ok(!listed.includes("generated/out.ts"));
  assert.ok(!listed.some((rel) => rel.startsWith("node_modules/")));
  assert.ok(!listed.includes("package-lock.json"));
  assert.ok(!listed.includes("photo.png"));
  assert.ok(!listed.includes("secret.bin"));
  assert.ok(!listed.includes("ignored-dir/skip.ts"));
  assert.ok(!listed.includes("dist/bundle.js"));

  const files = collectScanFiles(dir);
  const byPath = Object.fromEntries(files.map((file) => [file.path, file]));
  assert.ok(!byPath["src/generated_header.ts"]);
  assert.equal(byPath["src/billing/invoice.ts"]?.signals.touches_money, true);
  assert.equal(byPath["src/auth/login.ts"]?.signals.touches_auth, true);
  assert.equal(byPath["src/auth/login.ts"]?.signals.has_tests_nearby, true);
  assert.equal(byPath["db/migrations/001_init.sql"]?.signals.touches_migration, true);

  const lines: string[] = [];
  const summaries: string[] = [];
  const config = loadConfig({ TYPESAFE_API_KEY: "" }, { readUserStore: false });
  const { records, summary } = await runScan({
    root: dir,
    dryRun: true,
    config,
    writeLine: (line) => lines.push(line),
    writeSummary: (text) => summaries.push(text),
  });
  assert.equal(records.length, files.length);
  assert.ok(records.every((record) => record.answers === undefined));
  assert.ok(lines.every((line) => line.includes('"pass":1')));
  assert.match(summaries.join(""), /dry-run/);
  assert.match(summaries.join(""), /code_audit/);
  assert.equal(summary.dry_run, true);
});

test("cli dry-run on a fixture prints JSONL and does not call TypeSafe", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "mcp-jev-scan-cli-"));
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "mcp-jev-home-"));
  writeFixture(dir);
  const result = runCli(["scan", dir, "--dry-run"], { MCP_JEV_CONFIG: home });
  assert.equal(result.status, 0, result.stderr);
  const rows = result.stdout
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as { path: string; signals: { touches_money?: boolean } });
  const paths = rows.map((row) => row.path);
  assert.ok(paths.includes("src/billing/invoice.ts"));
  assert.ok(paths.includes("src/auth/login.ts"));
  assert.ok(!paths.includes("package-lock.json"));
  assert.ok(!paths.includes("secret.bin"));
  assert.match(result.stderr, /dry-run/);
  assert.ok(!result.stdout.includes("TYPESAFE_API_KEY"));
  assert.ok(!result.stderr.includes("sk-"));

  const viaCliJs = runCli(["scan", dir, "--dry-run"], { MCP_JEV_CONFIG: home }, "src/cli.ts");
  assert.equal(viaCliJs.status, 0, viaCliJs.stderr);
  assert.ok(viaCliJs.stdout.includes("src/billing/invoice.ts"));
});

test("scan without a key errors clearly unless dry-run", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "mcp-jev-scan-nokey-"));
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "mcp-jev-home-"));
  writeFixture(dir);
  const result = runCli(["scan", dir], { MCP_JEV_CONFIG: home, TYPESAFE_API_KEY: "" });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /TYPESAFE_API_KEY is not set/);
  assert.match(result.stderr, /config set-key/);
  assert.equal(result.stdout.trim(), "");
});

test("parseScanArgs reads flags and MCP_JEV_SCAN_CONCURRENCY", () => {
  const parsed = parseScanArgs(["./repo", "--pass2", "3", "--concurrency=4"], {});
  assert.equal(parsed.root, "./repo");
  assert.equal(parsed.pass2, 3);
  assert.equal(parsed.concurrency, 4);
  assert.equal(parsed.dryRun, false);
  const fromEnv = parseScanArgs([".", "--dry-run"], { MCP_JEV_SCAN_CONCURRENCY: "12" });
  assert.equal(fromEnv.concurrency, 12);
  assert.equal(fromEnv.dryRun, true);
  assert.throws(() => parseScanArgs([".", "--nope"], {}), /Unknown scan flag/);
});

test("runScan Pass 1 + Pass 2 reuse handleRunPack with a mocked systemOne", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "mcp-jev-scan-live-"));
  writeFixture(dir);
  const config = loadConfig({ TYPESAFE_API_KEY: "test-key" }, { readUserStore: false });
  const states: unknown[] = [];
  const { records, summary } = await runScan({
    root: dir,
    concurrency: 3,
    pass2: 2,
    config,
    systemOne: async (input) => {
      states.push(input.state);
      const pathName = String((input.state as { path?: string }).path ?? "");
      const excerpt = (input.state as { excerpt?: string }).excerpt;
      assert.equal(input.questions.primary_concern?.type, "choice");
      assert.equal(input.questions.hotspot_file, undefined);
      if (excerpt !== undefined) {
        assert.ok(excerpt.length <= MAX_EXCERPT_CHARS);
      }
      const severity = pathName.includes("billing") ? 2.4 : pathName.includes("auth/login.ts") ? 1.8 : 0.4;
      const concern = pathName.includes("billing") ? "verification" : "none";
      return {
        model: "jev-latest",
        answers: fakeAnswers(severity, concern),
        usage: { input_tokens: 4, output_tokens: 2 },
      } as SystemOneResult<Questions>;
    },
    writeLine: () => undefined,
    writeSummary: () => undefined,
  });

  const pass1 = records.filter((record) => record.pass === 1);
  const pass2 = records.filter((record) => record.pass === 2);
  assert.ok(pass1.length >= 4);
  assert.equal(pass2.length, 2);
  assert.ok(pass1.every((record) => !record.error));
  assert.ok(
    states.some((state) => {
      const rec = state as { excerpt?: string; signals?: { touches_migration?: boolean } };
      return rec.excerpt === undefined && rec.signals && !("touches_migration" in rec.signals);
    }),
  );
  assert.ok(states.some((state) => typeof (state as { excerpt?: string }).excerpt === "string"));
  assert.ok(summary.hottest_paths[0]?.includes("billing") || summary.top_severity[0]?.problem_severity === 2.4);
  assert.ok(summary.primary_concern.verification >= 1);
  assert.match(formatSummaryTable(summary), /Top severity/);
  assert.equal(problemSeverity(pass1.find((r) => r.path.includes("billing"))?.answers), 2.4);
  assert.equal(primaryConcern(pass1.find((r) => r.path.includes("billing"))?.answers), "verification");
});

test("rankForPass2 orders by problem_severity then path", () => {
  const records: ScanRecord[] = [
    { pass: 1, path: "b.ts", language: "ts", role_hint: "other", signals: extractSignals("b.ts", "", []), answers: fakeAnswers(1.0, "none") },
    { pass: 1, path: "a.ts", language: "ts", role_hint: "other", signals: extractSignals("a.ts", "", []), answers: fakeAnswers(2.0, "verification") },
    { pass: 1, path: "c.ts", language: "ts", role_hint: "other", signals: extractSignals("c.ts", "", []), error: { code: "x", message: "nope" } },
  ];
  assert.deepEqual(
    rankForPass2(records, 1).map((record) => record.path),
    ["a.ts"],
  );
});
